export const inputMovies = [
    {
        id: "IdNombre",
        name: "nombre",
        type: "text",
        className: "col-10 col-md-5 col-lg-5 m-auto mt-2 mb-2",
        label: "Nombre",
        required: true,
    },
    {
        id: "IdIdioma",
        name: "idioma",
        type: "select",
        className: "col-10 col-md-5 col-lg-5 m-auto mt-2 mb-2",
        label: "Idioma",
        required: true,
    },
    {
        id: "IdClasificacion",
        name: "clasificacion",
        type: "select",
        className: "col-10 col-md-5 col-lg-3 m-auto mt-2 mb-2",
        label: "Clasificacion",
        required: true,
    },
    {
        id: "IdDuracion",
        name: "duracion",
        type: "number",
        className: "col-10 col-md-5 col-lg-3 m-auto mt-2 mb-2",
        logo: "fa-solid fa-fingerprint",
        label: "Duracion (min)",
        required: true,
    },
    {
        id: "IdFechaEstreno",
        name: "fecha_estreno",
        type: "date",
        className: "col-10 col-md-5 col-lg-3 m-auto mt-2 mb-2",
        label: "Fecha de Estreno",
        required: true,
    },
    {
        id: "IdTrailer",
        name: "trailer",
        type: "text",
        className: "col-10 col-md-5 col-lg-5 m-auto mt-2 mb-2",
        label: "URL del Trailer",
        required: true,
    },
    {
        id: "IdDirector",
        name: "director",
        type: "text",
        className: "col-10 col-md-5 col-lg-5 m-auto mt-2 mb-2",
        label: "Director",
        required: true,
    },
];
